---
permalink: install-vapp/task_download_unified_manager_ova_file.html 
sidebar: sidebar 
keywords: download, unified manager, installation, file 
summary: Descargue el archivo de instalación de Unified Manager desde el sitio de soporte de NetApp para poner en marcha Unified Manager como dispositivo virtual. 
---
= Descargue el archivo de instalación de Unified Manager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Descargue el archivo de instalación de Unified Manager desde el sitio de soporte de NetApp para poner en marcha Unified Manager como dispositivo virtual.

*Lo que necesitará*

Debe tener las credenciales de inicio de sesión en el sitio de soporte de NetApp.

El archivo de instalación es `.tar` un archivo que contiene un certificado raíz, un `README` archivo y un `OVA` archivo que contiene el software Unified Manager configurado para un dispositivo virtual.

.Pasos
. Inicie sesión en el sitio de soporte de NetApp y desplácese hasta la página de descarga de Unified Manager:
+
https://mysupport.netapp.com/site/products/all/details/activeiq-unified-manager/downloads-tab["Sitio de soporte de NetApp"]

. Seleccione la versión requerida de Unified Manager y acepte el contrato de licencia para usuarios finales (CLUF).
. Descargue y guarde el `.tar` archivo para la instalación de VMware vSphere en un directorio local o un directorio de red accesible para vSphere Client.
. Compruebe la suma de comprobación para asegurarse de que el software se ha descargado correctamente.
. Desplácese hasta el directorio donde descargó el `.tar` archivo e introduzca el siguiente comando en la ventana de terminal para expandir el paquete de Unified Manager:
+
[listing]
----
tar -xvzf ActiveIQUnifiedManager-<version>.tar.gz
----
+
El archivo requerido `OVA`, un certificado raíz y `README` un archivo para Unified Manager se descomprimen en el directorio de destino.

. Verifique la integridad `OVA` del archivo siguiendo los pasos proporcionados en el `README` archivo.

