---
permalink: install-linux/task_selinux_requirements_for_mounting_opt_netapp.html 
sidebar: sidebar 
keywords: unified manager, selinux requirements, mounting, nfs, cifs, share 
summary: Si tiene pensado montar /opt/netapp o /opt/netapp/data en un dispositivo NAS o SAN y tiene SELinux activado, tiene que tener en cuenta los siguientes aspectos. 
---
= Requisitos de SELinux en recursos compartidos NFS y CIFS
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si está planeando montar `/opt/netapp` o `/opt/netapp/data` en un dispositivo NAS o SAN y tiene activado SELinux, debe tener en cuenta algunas consideraciones.

Si planea montar `/opt/netapp` o `/opt/netapp/data` desde cualquier lugar que no sea el sistema de archivos raíz y tiene activado SELinux en su entorno, debe definir el contexto correcto para los directorios montados. Para el escenario aplicable en su entorno, siga estos pasos para configurar y confirmar el contexto SELinux correcto.



== Configuración del contexto SELinux cuando `/opt/netapp/data` está montado

Si ha montado `/opt/netapp/data` en el sistema y SELinux está definido en `Enforcing`, asegúrese de que el tipo de contexto SELinux para está definido en `mysqld_db_t`, que es el elemento de contexto por defecto para `/opt/netapp/data` la ubicación de los archivos de base de datos.

. Ejecute este comando para comprobar el contexto:
+
`ls -dZ /opt/netapp/data`

+
Una salida de muestra:

+
[listing]
----
drwxr-xr-x. mysql root unconfined_u:object_r:default_t:s0 /opt/netapp/data
----
+

NOTE: En esta salida, el contexto es `default_t`. Debe cambiar este contexto a `mysqld_db_t`.

. Realice estos pasos para definir el contexto en función de cómo se ha montado `/opt/netapp/data`.
+
.. Ejecute los siguientes comandos para definir el contexto en `mysqld_db_t`:
`semanage fcontext -a -t mysqld_db_t "/opt/netapp/data"
`restorecon -R -v /opt/netapp/data`
.. Si ha configurado `/opt/netapp/data` en `/etc/fstab`, debe editar el `/etc/fstab` archivo. Para `/opt/netapp/data/` la opción de montaje, añada la etiqueta de MySQL como:
+
`context=system_u:object_r:mysqld_db_t:s0`

.. Desmonte y vuelva a montar `/opt/netapp/data/` para activar el contexto.
.. Si tiene un montaje NFS directo, ejecute el siguiente comando para establecer el contexto en `mysqld_db_t`:
+
`mount <nfsshare>:/<mountpoint> /opt/netapp/data -o context=system_u:object_r:mysqld_db_t:s0`



. Compruebe si el contexto está configurado correctamente:


`ls -dZ /opt/netapp/data/`

Una salida de muestra:

[listing]
----
drwxr-xr-x. mysql root unconfined_u:object_r:mysqld_db_t:s0 /opt/netapp/data/
----


== Configurar el contexto SELinux cuando `/opt/netapp` está montado, y `/opt/netapp/data/` también se monta por separado

En este escenario, al principio, debe definir el contexto para `/opt/netapp/data/` como se describe en la sección anterior. Después de definir el contexto correcto para `/opt/netapp/data/`, asegúrese de que el directorio principal `/opt/netapp` no tiene el contexto SELinux definido en `file_t`.

.Pasos
. Ejecute este comando para comprobar el contexto:
+
`ls -dZ /opt/netapp`

+
Una salida de muestra:

+
[listing]
----
drwxr-xr-x. mysql root unconfined_u:object_r:file_t:s0 /opt/netapp
----
+
En esta salida, se debe cambiar el contexto `file_t`. Los siguientes comandos establecen el contexto en `usr_t`. Puede definir el contexto en cualquier valor que no sea `file_t` basado en sus requisitos de seguridad.

. Realice estos pasos para definir el contexto, en función de la forma en que ha montado `/opt/netapp`.
+
.. Ejecute los siguientes comandos para configurar el contexto:




[listing]
----
semanage fcontext -a -t usr_t "/opt/netapp"
restorecon -v /opt/netapp
----
. Si ha configurado `/opt/netapp` en `/etc/fstab`, debe editar el `/etc/fstab` archivo. Para `/opt/netapp` la opción de montaje, añada la etiqueta de MySQL como:
+
`context=system_u:object_r:usr_t:s0`

. Desmonte y, a continuación, monte de nuevo `/opt/netapp` para activar el contexto.
. Si tiene un montaje NFS directo, ejecute el siguiente comando para establecer el contexto:
+
`mount <nfsshare>:/<mountpoint> /opt/netapp -o context=system_u:object_r:usr_t:s0`

+
.. Compruebe si el contexto está configurado correctamente:
+
`ls -dZ /opt/netapp`

+
Salida de muestra





[listing]
----
drwxr-xr-x. mysql root unconfined_u:object_r:usr_t:s0 /opt/netapp
----


== Configuración del contexto SELinux cuando `/opt/netapp` está montado y `/opt/netapp/data/` no se monta por separado

Si ha montado  `/opt/netapp` en el sistema y SELinux está definido en `Enforcing`, asegúrese de que el tipo de contexto SELinux para está definido en `mysqld_db_t`, que es el elemento de contexto por defecto para `/opt/netapp` la ubicación de los archivos de base de datos.

.Pasos
. Ejecute este comando para comprobar el contexto:
+
`ls -dZ /opt/netapp`

+
Una salida de muestra:

+
[listing]
----
drwxr-xr-x. mysql root unconfined_u:object_r:default_t:s0 /opt/netapp
----
+

NOTE: En esta salida, el contexto es `default_t`. Debe cambiar este contexto a `mysqld_db_t`.

. Realice los siguientes pasos para definir el contexto en función de cómo se ha montado `/opt/netapp`.
+
.. Ejecute los siguientes comandos para definir el contexto en `mysqld_db_t`:
`semanage fcontext -a -t mysqld_db_t "/opt/netapp"
`restorecon -R -v /opt/netapp`
.. Si ha configurado `/opt/netapp` en `/etc/fstab`, edite el `/etc/fstab` archivo. Para `/opt/netapp/` la opción de montaje, añada la etiqueta de MySQL como:
`context=system_u:object_r:mysqld_db_t:s0`
.. Desmonte y, a continuación, monte de nuevo `/opt/netapp/` para activar el contexto.
.. Si tiene un montaje NFS directo, ejecute el siguiente comando para establecer el contexto en `mysqld_db_t`:
`mount <nfsshare>:/<mountpoint> /opt/netapp -o context=system_u:object_r:mysqld_db_t:s0`


. Compruebe si el contexto está configurado correctamente:


`ls -dZ /opt/netapp/`

Una salida de muestra:

[listing]
----
drwxr-xr-x. mysql root unconfined_u:object_r:mysqld_db_t:s0 /opt/netapp/
----
'''